### ISSUE TITLE
Error in average_3d_ffd

### ISSUE THREAD

**Issue by karllandheer** [baiwenjia/ukbb_cardiac#8]
Hello, when I try to run average_3d_ffd (necessary to calculate the strain values) I get this error:

double free or corruption (out)
Aborted (core dumped)

Do you have any idea on how I can remedy this?

**Comment by baiwenjia** [comment]
Sorry, this is a programme that I wrote using C++ (nowadays most people use Python...) and linked it to the MIRTK library, developed in our lab. Currently, I do not have a Python alternative for this. You may try perform motion tracking without this command, i.e. changing the code to just perform forward image registration. In this way, motion tracking can still work. However, the strain curve may have the drift effect (i.e. the (N-1)-th frame will not have zero strain, although it is close to end-diastolic frame). More information about drift effect can be found in this paper (https://www.sciencedirect.com/science/article/pii/S1361841513000388).
