### ISSUE TITLE
Unable to import from relative packages

### ISSUE THREAD

**Issue by atran126** [baiwenjia/ukbb_cardiac#9]
When I run the demo_pipeline.py as is, I get an error from each of the scripts that call functions from another script. For example, eval_wall_thickness.py gives the error "ModuleNotFoundError: No module named 'common'" for 
`from common.cardiac_utils import *'

How should I fix this error?

**Comment by baiwenjia** [comment]
The module common can be imported, if you add the git repository to the environment variable PYTHON_PATH, such as
`export PYTHONPATH=YOUR_GIT_REPOSITORY_PATH:"${PYTHONPATH}"`
